-- +goose Up
CREATE TABLE halls (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL, 
    capacity smallint NOT NULL
);

-- +goose Down
DROP TABLE IS EXISTS halls;