-- +goose Up
CREATE TABLE seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hall_id BIGINT NOT NULL REFERENCES halls (id) ON DELETE CASCADE,
    row TEXT NOT NULL,
    number SMALLINT NOT NULL CHECK (number > 0),
    UNIQUE (hall_id, row, number)
);

-- +goose Down
DROP TABLE IF EXISTS seats;