-- +goose Up
CREATE TABLE movies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(100) NOT NULL,
    description text,
    duration INTERVAL NOT NULL,
    image BYTEA,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

-- +goose Down
DROP TABLE IF EXISTS movies;