-- +goose Up
CREATE TABLE sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hall_id INTEGER not null REFERENCES halls (id),
    movie_id INTEGER not null REFERENCES movies (id),
    status varchar(10) default 'scheduled' check (status in ('scheduled', 'active', 'cancelled'))
    start_at timestamp not null,
    end_at timestamp not null,
    created_at timestamp not null DEFAULT now()
);

-- +goose Down
DROP TABLE IF EXISTS sessions;