-- +goose Up
CREATE TABLE bookings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id INTEGER not null REFERENCES session (id) on delete cascade,
    user_id UUID NOT NULL,
    seat_number integer not null check (seat_number > 0),
    status varchar(10) DEFAULT 'pending' check (status in ('pending', 'confirmed', 'cancelled', 'completed')),
    created_at timestamp not null DEFAULT now(),
);

-- +goose Down
DROP TABLE IF EXISTS bookings;