-- +goose Up
CREATE TABLE sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hall_id BIGINT NOT NULL REFERENCES halls (id),
    movie_id BIGINT NOT NULL REFERENCES movies (id),
    status VARCHAR(10) DEFAULT 'scheduled'
        CHECK (status IN ('scheduled', 'active', 'cancelled')),
    start_at TIMESTAMP NOT NULL,
    end_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

-- +goose Down
DROP TABLE IF EXISTS sessions;